CREATE DATABASE ecommmerce_sales_project;

USE ecommmerce_sales_project;

SHOW TABLES;

SELECT *
FROM ecommerce_sales_data
LIMIT 10;



SELECT *
FROM ecommerce_sales_data
WHERE `Order Date` IS NULL
   OR `Product Name` IS NULL
   OR Category IS NULL
   OR Region IS NULL
   OR Quantity IS NULL
   OR Sales IS NULL
   OR Profit IS NULL;

SELECT `Order Date`,`Product Name`,Category,Region,Quantity,Sales,Profit,
       COUNT(*) AS duplicate_count
FROM ecommerce_sales_data
GROUP BY `Order Date`,`Product Name`,Category,Region,Quantity,Sales,Profit
HAVING COUNT(*) > 1;

SELECT *
FROM ecommerce_sales_data
WHERE Quantity < 0
   OR Sales < 0;
   
   SELECT COUNT(*) 
FROM ecommerce_sales_data;

#. What is the total sales revenue generated by the company?
SELECT SUM(Sales) AS Total_Sales_Revenue
FROM ecommerce_sales_data;

#. How do sales vary across different regions?
SELECT Region,
       SUM(Sales) AS Total_Sales
FROM ecommerce_sales_data
GROUP BY Region
ORDER BY Total_Sales DESC;

#.Which products contribute the most to overall sales?
SELECT 'Product Name',
       SUM(Sales) AS Total_Product_Sales
FROM ecommerce_sales_data
GROUP BY 'Product Name'
ORDER BY Total_Product_Sales DESC;



#. Which categories generate the highest sales revenue?
SELECT Category,
       SUM(Sales) AS Total_Category_Sales
FROM ecommerce_sales_data
GROUP BY Category
ORDER BY Total_Category_Sales DESC;


#.	How does sales performance change over time (monthly/yearly)?
#Monthly
SELECT MONTH(`Order Date`) AS Month,
       SUM(Sales) AS Monthly_Sales
FROM ecommerce_sales_data
GROUP BY MONTH(`Order Date`)
ORDER BY Month;
#Yearly
SELECT YEAR(`Order Date`) AS Year,
       SUM(Sales) AS Yearly_Sales
FROM ecommerce_sales_data
GROUP BY YEAR(`Order Date`)
ORDER BY Year;


#.	What is the total profit earned by the company?
SELECT ROUND(SUM(Profit)) As Total_Profit
FROM ecommerce_sales_data;


#.Which products generate the highest profit?
SELECT `Product Name`,
       ROUND(SUM(Profit)) AS Total_Product_Profit
FROM ecommerce_sales_data
GROUP BY `Product Name`
ORDER BY Total_Product_Profit DESC;


#.Which products generate the highest revenue?
SELECT `Product Name`,
       SUM(Sales) AS Total_Revenue
FROM ecommerce_sales_data
GROUP BY `Product Name`
ORDER BY Total_Revenue DESC;


#. Which product category sells the most units?
SELECT Category,
       SUM(Quantity) AS Total_Units_Sold
FROM ecommerce_sales_data
GROUP BY Category
ORDER BY Total_Units_Sold DESC;

# .Which category generates the most profit?
SELECT Category,
       SUM(Profit) AS Total_Profit
FROM ecommerce_sales_data
GROUP BY Category
ORDER BY Total_Profit DESC;

#. How does sales distribution vary across categories?
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM ecommerce_sales_data
GROUP BY Category
ORDER BY Total_Sales DESC;

#.Which region generates the highest sales revenue?
SELECT Region,
       SUM(Sales) AS Total_Sales_Revenue
FROM ecommerce_sales_data
GROUP BY Region
ORDER BY Total_Sales_Revenue DESC;

#. Which region generates the highest profit?
SELECT Region,
       SUM(Profit) AS Total_Profit
FROM ecommerce_sales_data
GROUP BY Region
ORDER BY Total_Profit DESC;

#. Which region sells the most quantity of products?
SELECT Region,
       SUM(Quantity) AS Total_Quantity_Sold
FROM ecommerce_sales_data
GROUP BY Region
ORDER BY Total_Quantity_Sold DESC;

#. Which products are most popular in each region?
SELECT Region,`Product Name`,
       SUM(Quantity) AS Total_Quantity_Sold
FROM ecommerce_sales_data
GROUP BY Region, `Product Name`
ORDER BY Region, Total_Quantity_Sold DESC;

#. Are there regions with high sales but low profit margins?
SELECT Region, SUM(Sales) AS Total_Sales, SUM(Profit) AS Total_Profit,
       (SUM(Profit) / SUM(Sales)) * 100 AS Profit_Margin
FROM ecommerce_sales_data
GROUP BY Region
ORDER BY Total_Sales DESC;

# . Which month records the highest sales?
SELECT MONTHNAME(`Order Date`) AS Month, SUM(Sales) AS Total_Sales
FROM ecommerce_sales_data
GROUP BY MONTH(`Order Date`), MONTHNAME(`Order Date`)
ORDER BY Total_Sales DESC LIMIT 1;

#. Which month records the highest profit?
SELECT MONTHNAME(`Order Date`) AS Month, SUM(Profit) AS Total_Profit
FROM ecommerce_sales_data
GROUP BY MONTH(`Order Date`), MONTHNAME(`Order Date`)
ORDER BY Total_Profit DESC LIMIT 1;

#. Are there seasonal patterns in sales?
SELECT MONTHNAME(`Order Date`) AS Month, SUM(Sales) AS Total_Sales
FROM ecommerce_sales_data
GROUP BY MONTH(`Order Date`), MONTHNAME(`Order Date`)
ORDER BY MONTH(`Order Date`);

# Which month records the highest profit?
SELECT MONTHNAME(`Order Date`) AS Month, SUM(Profit) AS Total_Profit
FROM ecommerce_sales_data
GROUP BY MONTH(`Order Date`), MONTHNAME(`Order Date`)
ORDER BY Total_Profit DESC LIMIT 1;

SELECT *
FROM ecommerce_sales_data;
